### ISSUE TITLE
微信小程序报signature错误

### ISSUE THREAD

**Issue by slarkerino** [EasyAbp/WeChatManagement#18]
在本地开发环境下可以正常登录，但是发布到服务器上就一直报错。
![image](https://user-images.githubusercontent.com/7014849/108591684-e6dce880-73a4-11eb-9962-e37386d3a8fb.png)
2021-02-20 17:40:39.263 +08:00 [ERR] Exception of type 'EasyAbp.Abp.WeChat.Common.Exceptions.SignatureInvalidException' was thrown.
EasyAbp.Abp.WeChat.Common.Exceptions.SignatureInvalidException: Exception of type 'EasyAbp.Abp.WeChat.Common.Exceptions.SignatureInvalidException' was thrown.
   at EasyAbp.Abp.WeChat.MiniProgram.Infrastructure.SignatureChecker.Check(String rawData, String sessionKey, String signature)
   at EasyAbp.WeChatManagement.MiniPrograms.Login.LoginAppService.GetLoginResultAsync(LoginInput input)
   at EasyAbp.WeChatManagement.MiniPrograms.Login.LoginAppService.LoginAsync(LoginInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1717(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-02-20 17:40:39.264 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2021-02-20 17:40:39.265 +08:00 [INF] Executed action EasyAbp.WeChatManagement.MiniPrograms.Login.LoginController.LoginAsync (EasyAbp.WeChatManagement.MiniPrograms.HttpApi) in 159.1997ms

**Comment by gdlcf88** [comment]
本地也需要使用相同的分布式Redis源，与服务器共享AccessToken

**Comment by slarkerino** [comment]
@gdlcf88 请问下redis这里的配置是和别的abp模块一样嘛？

**Comment by gdlcf88** [comment]
参考：https://github.com/EasyAbp/WeChatManagement/issues/15#issuecomment-769718739

**Comment by slarkerino** [comment]
Problem solved. Frontend did not get authcode before getting userinfo which caused  signature invalidation error.
